server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: system_route
          uri: lb://STUDY-SYSTEM
          predicates:
            - Path=/sysApi/**
          filters:
            - RewritePath=/sysApi/(?<segment>.*),/$\{segment}
        - id: oneMap_route
          uri: http://localhost:3000
          predicates:
            - Path=/oneMapApi/**
          filters:
            - RewritePath=/oneMapApi/(?<segment>.*),/$\{segment}
        - id: business_route
          uri: lb://STUDY-BUSINESS
          predicates:
            - Path=/busApi/**
          filters:
            - RewritePath=/busApi/(?<segment>.*),/$\{segment}
        - id: webBack_route
          uri: http://localhost:10007
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<segment>.*),/$\{segment}
  application:
    name: study-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka/  # 服务中心地址